name: ToDo Tests
on:
  push:
    branches: github-workflow
jobs:
  todo_tests:
    name: Run ToDo tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Say hello
        run: echo Hello
